//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Argument
    {
        public int OrderID { get; set; }
        public int ArgumentID { get; set; }
        public Nullable<bool> ChangeorReturn { get; set; }
        public string Reason { get; set; }
        public byte[] Image1 { get; set; }
        public byte[] Image2 { get; set; }
        public byte[] Image3 { get; set; }
        public int ArgumentTypeID { get; set; }
    
        public virtual ArgumentType ArgumentType { get; set; }
        public virtual Order Order { get; set; }
    }
}
