//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int SalesCourtID { get; set; }
        public int MemberID { get; set; }
        public string Comment1 { get; set; }
        public byte Star { get; set; }
        public int CommentID { get; set; }
        public byte[] Imaga1 { get; set; }
        public byte[] Imaga2 { get; set; }
        public byte[] Image3 { get; set; }
    
        public virtual MemberAccount MemberAccount { get; set; }
        public virtual Product Product { get; set; }
    }
}
