//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public int ProductDetailID { get; set; }
        public int ShipperID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime ShippingDate { get; set; }
        public System.DateTime RecieveDate { get; set; }
        public string OutAdr { get; set; }
        public int ShippingStatusID { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual Shipper Shipper { get; set; }
        public virtual ShippingStatuses ShippingStatuses { get; set; }
    }
}
